stackabletech/demos

demos/hbase-hdfs-load-cycling-data/create-hfile-and-import-to-hbase.yaml, demos/hbase-hdfs-load-cycling-data/distcp-cycling-data.yaml
Cherry-picked from stackabletech/stackablectl#292
=> Set HADOOP_USER_NAME in hbase-hdfs-load-cycling-data demo

docs/modules/demos/pages/data-lakehouse-iceberg-trino-spark.adoc
Part of https://github.com/stackabletech/issues/issues/455
=> docs: Update demo link

stacks/authentication/openldap-tls-authenticationclass.yaml
Port of https://github.com/stackabletech/stackablectl/pull/297
=> fix: LDAP bind credential fix for openldap stack

stacks/data-lakehouse-iceberg-trino-spark/trino.yaml, stacks/dual-hive-hdfs-s3/trino.yaml, stacks/trino-iceberg/trino.yaml, stacks/trino-superset-s3/trino.yaml
Relates to https://github.com/stackabletech/trino-operator/pull/517
=> fix: Add missing OPA rules for Trino batched API

demos/data-lakehouse-iceberg-trino-spark/create-nifi-ingestion-job.yaml, demos/data-lakehouse-iceberg-trino-spark/setup-superset.yaml, demos/demos-v2.yaml, demos/nifi-kafka-druid-earthquake-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-earthquake-data/setup-superset.yaml, demos/nifi-kafka-druid-water-level-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-water-level-data/setup-superset.yaml, demos/signal-processing/create-nifi-ingestion-job.yaml, demos/spark-k8s-anomaly-detection-taxi-data/setup-superset.yaml, demos/trino-taxi-data/setup-superset.yaml, docs/modules/demos/pages/data-lakehouse-iceberg-trino-spark.adoc, stacks/airflow/airflow.yaml, stacks/signal-processing/jupyterhub.yaml, stacks/stacks-v2.yaml
=> fix: use release-24.3 branch references

demos/data-lakehouse-iceberg-trino-spark/create-nifi-ingestion-job.yaml, demos/data-lakehouse-iceberg-trino-spark/setup-superset.yaml, demos/demos-v2.yaml, demos/nifi-kafka-druid-earthquake-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-earthquake-data/setup-superset.yaml, demos/nifi-kafka-druid-water-level-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-water-level-data/setup-superset.yaml, demos/signal-processing/create-nifi-ingestion-job.yaml, demos/spark-k8s-anomaly-detection-taxi-data/setup-superset.yaml, demos/trino-taxi-data/setup-superset.yaml, stacks/_templates/jupyterhub.yaml, stacks/end-to-end-security/superset.yaml, stacks/signal-processing/jupyterhub.yaml, stacks/stacks-v2.yaml
=> fix: use release-24.7 branch references

stacks/data-lakehouse-iceberg-trino-spark/trino.yaml, stacks/end-to-end-security/opa.yaml, stacks/keycloak-opa-poc/opa.yaml, stacks/trino-iceberg/trino.yaml, stacks/trino-superset-s3/trino.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
> [!CAUTION]
> This PR is raised against the `next` branch so that demos aren't broken (resolved in future by https://github.com/stackabletech/stackable-cockpit/issues/310)
=> chore(opa): bump to 0.67.1

demos/end-to-end-security/create-spark-report.yaml
Intermediate fix to mitigate non ma conformity in tools-image
=> fix for end-to-end-demo

stacks/end-to-end-security/trino-policies.yaml
Part of https://github.com/stackabletech/opa-operator/issues/617
=> docs: Document how to switch to uif wrapper

.github/workflows/pr_pre-commit.yml, .markdownlint.yaml, .pre-commit-config.yaml, .yamllint.yaml
Part of https://github.com/stackabletech/issues/issues/637
This PR adds a `pre-commit` workflow and accompanying config files.
=> ci: Add pre-commit workflow

docs/modules/demos/pages/trino-iceberg.adoc, stacks/data-lakehouse-iceberg-trino-spark/trino.yaml, stacks/dual-hive-hdfs-s3/trino.yaml, stacks/end-to-end-security/trino-regorules.yaml, stacks/end-to-end-security/trino.yaml, stacks/keycloak-opa-poc/trino.yaml, stacks/trino-iceberg/trino.yaml, stacks/trino-superset-s3/trino.yaml
Part of https://github.com/stackabletech/issues/issues/626
=> chore(trino): bump version to 455

demos/data-lakehouse-iceberg-trino-spark/create-spark-ingestion-job.yaml, demos/end-to-end-security/create-spark-report.yaml, demos/spark-k8s-anomaly-detection-taxi-data/create-spark-anomaly-detection-job.yaml, stacks/airflow/airflow.yaml
part of https://github.com/stackabletech/docker-images/issues/838
=> chore(spark): version 3.5.2

demos/hbase-hdfs-load-cycling-data/distcp-cycling-data.yaml, demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data/load-test-data.yaml, demos/spark-k8s-anomaly-detection-taxi-data/load-test-data.yaml, demos/trino-taxi-data/load-test-data.yaml, stacks/dual-hive-hdfs-s3/hdfs.yaml, stacks/end-to-end-security/hdfs.yaml, stacks/hdfs-hbase/hdfs.yaml, stacks/jupyterhub-pyspark-hdfs/hdfs.yaml, stacks/keycloak-opa-poc/hdfs.yaml
part of: https://github.com/stackabletech/docker-images/issues/835
=> chore: bump hdfs version to 3.4.0

.github/workflows/dev_nifi.yaml
Follow up of failed workflow run on https://github.com/stackabletech/demos/pull/103
=> ci: change path in nifi image workflow

.github/workflows/dev_jupyter-pyspark-with-alibi-detect.yaml, .github/workflows/dev_pyspark-k8s-with-scikit-learn.yaml, demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data/Dockerfile, demos/signal-processing/Dockerfile-jupyter
Part of https://github.com/stackabletech/infrastructure/issues/143
=> ci: Add workflows for pyspark images

demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data/Dockerfile, demos/signal-processing/Dockerfile-jupyter
Follow up of https://github.com/stackabletech/demos/pull/108
=> ci: Fix paths to requirements files in Dockerfiles

stacks/airflow/airflow.yaml
Behaviour changed in the airflow-operator so the failure states need to be adjusted.
=> fix: remove unknown from failure states

demos/hbase-hdfs-load-cycling-data/create-hfile-and-import-to-hbase.yaml, demos/hbase-hdfs-load-cycling-data/distcp-cycling-data.yaml, docs/modules/demos/pages/hbase-hdfs-load-cycling-data.adoc
Part of https://github.com/stackabletech/issues/issues/658
- Fixes the data loading for the demo (see https://github.com/stackabletech/docker-images/issues/793).
- Improve the docs.
- Tidy up job scripts.
=> chore(demo/hbase-hdfs-load-cycling-data-demo): Update demo

stacks/end-to-end-security/superset.yaml, stacks/keycloak-opa-poc/superset.yaml, stacks/nifi-kafka-druid-superset-s3/superset.yaml, stacks/trino-superset-s3/superset.yaml
Part of https://github.com/stackabletech/docker-images/issues/970
=> chore(superset): Bump to 4.1.1

stacks/data-lakehouse-iceberg-trino-spark/trino.yaml, stacks/dual-hive-hdfs-s3/trino.yaml, stacks/end-to-end-security/opa.yaml, stacks/keycloak-opa-poc/opa.yaml, stacks/trino-iceberg/trino.yaml, stacks/trino-superset-s3/trino.yaml
Part of https://github.com/stackabletech/docker-images/issues/998
=> chore(opa): bump to 1.0.1

demos/hbase-hdfs-load-cycling-data/create-hfile-and-import-to-hbase.yaml, stacks/hdfs-hbase/hbase.yaml
Part of https://github.com/stackabletech/docker-images/issues/972
=> chore(hbase): Bump to 2.6.1

stacks/keycloak-opa-poc/druid.yaml, stacks/nifi-kafka-druid-superset-s3/druid.yaml
Part of https://github.com/stackabletech/docker-images/issues/965
=> chore(druid): Bump to 31.0.1

stacks/airflow/airflow.yaml
Part of https://github.com/stackabletech/docker-images/issues/1017
=> chore: Update Airflow to 2.10.4

stacks/data-lakehouse-iceberg-trino-spark/hive-metastores.yaml, stacks/dual-hive-hdfs-s3/hive.yaml, stacks/end-to-end-security/hive-metastore.yaml, stacks/spark-trino-superset-s3/hive-metastore.yaml, stacks/trino-iceberg/hive-metastores.yaml, stacks/trino-superset-s3/hive-metastore.yaml
part of https://github.com/stackabletech/docker-images/issues/1019
=> chore: Update Hive to 4.0.1

demos/data-lakehouse-iceberg-trino-spark/create-spark-ingestion-job.yaml, demos/end-to-end-security/create-spark-report.yaml, demos/spark-k8s-anomaly-detection-taxi-data/create-spark-anomaly-detection-job.yaml, stacks/airflow/airflow.yaml
Part of https://github.com/stackabletech/docker-images/issues/1016
Successfully tested the anomaly detection demo.
=> chore: Update Spark to 3.5.5

docs/modules/demos/pages/trino-iceberg.adoc, stacks/data-lakehouse-iceberg-trino-spark/trino.yaml, stacks/dual-hive-hdfs-s3/trino.yaml, stacks/end-to-end-security/trino.yaml, stacks/keycloak-opa-poc/trino.yaml, stacks/trino-iceberg/trino.yaml, stacks/trino-superset-s3/trino.yaml
Part of https://github.com/stackabletech/docker-images/issues/971.
=> feat(trino): Use 470

stacks/end-to-end-security/hive-metastore.yaml
Spark job fails with 4.0.1
```
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_objects_by_name'                                                                                                                                           
at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)                                                                                                                                                                    
at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_objects_by_name(ThriftHiveMetastore.java:1544)                                                                                                           
at …
```
=> fix(end-to-end-security): Downgrade Hive metastore to 4.0.0

docs/antora.yml
=> fix(docs): Adjust version from  nightly to 25.3 in antora.yaml

stacks/hdfs-hbase/hbase.yaml
N.B. depends on https://github.com/stackabletech/hbase-operator/pull/639 and https://github.com/stackabletech/docker-images/pull/1159
=> chore: HBase demo - add listener class fields

docs/modules/demos/pages/spark-k8s-anomaly-detection-taxi-data.adoc
* docs: spark anomaly detection, remove dead links and update ports
* Update docs/modules/demos/pages/spark-k8s-anomaly-detection-taxi-data.adoc
Co-authored-by: Andrew Kenworthy <1712947+adwk67@users.noreply.github.com>
---------
Co-authored-by: Andrew Kenworthy <1712947+adwk67@users.noreply.github.com>
=> docs: spark anomaly detection, remove dead links and update ports (#239)

demos/data-lakehouse-iceberg-trino-spark/create-spark-ingestion-job.yaml
- **Improve resource/topic wait script (#261)**
- **update broker url**
=> backport: lake demo, wait for resources

docs/modules/demos/pages/hbase-hdfs-load-cycling-data.adoc
> [!TIP]
> See companion PR: https://github.com/stackabletech/demos/pull/273
The listener endpoints are updated, as well as a few minor formatting line-breaks.
=> fix(demo/hbase-hdfs-load-cycling-data): Update stacklet addresses

stacks/keycloak-opa-poc/druid.yaml, stacks/nifi-kafka-druid-superset-s3/druid.yaml
Part of https://github.com/stackabletech/docker-images/issues/1234
=> chore: Bump druid version for 25.11.0

demos/logging/zookeeper.yaml, stacks/data-lakehouse-iceberg-trino-spark/zookeeper.yaml, stacks/dual-hive-hdfs-s3/hdfs.yaml, stacks/end-to-end-security/zookeeper.yaml, stacks/hdfs-hbase/zookeeper.yaml, stacks/jupyterhub-pyspark-hdfs/zookeeper.yaml, stacks/keycloak-opa-poc/zookeeper.yaml, stacks/nifi-kafka-druid-superset-s3/zookeeper.yaml
Part of https://github.com/stackabletech/docker-images/issues/1275
=> chore: Bump zookeeper version for 25.11.0
