stacks/_templates/jupyterhub.yaml
Jupyter helm-chart < 3.0.0 has the bug https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3128 and does not run on k8s 1.27
=> fix: Disable user-scheduler in juypter helm-chart

demos/demos-v2.yaml, docs/modules/demos/pages/nifi-kafka-druid-earthquake-data.adoc, docs/modules/demos/pages/nifi-kafka-druid-water-level-data.adoc, stacks/nifi-kafka-druid-superset-s3/druid.yaml, stacks/stacks-v2.yaml
=> fix: Increase memory for Druid middlemanager in nifi-kafka-druid-superset-s3

stacks/stacks-v2.yaml
The listener operator is required for HDFS so I added it to all of the stacks that use HDFS but did not install it.
=> Added listener operator to all the stacks that are using HDFS

stacks/keycloak-opa-poc/setup-keycloak.yaml, stacks/stacks-v2.yaml
If the setup-keycloak job fails the first time it is run it will fail on all subsequent attempts. This is because it will download and unpack the keycloak zip file each time, but on subsequent attempts fails when unzip prompts for user input before overwriting files. Added the -o flag to unzip to force overwriting of existing files.
=> Keycloak opa poc fix

docs/modules/demos/pages/nifi-kafka-druid-water-level-data.adoc
Just a small fix to a typo in a url for the pegelonline website.
=> fix: fix url typo for pegelonline

stacks/stacks-v2.yaml
We do this to avoid getting `WARN  Unsuccessful data error parse: 404 page not found` during `stackablectl stacklet list`
=> Add listener-operator to every stack

stacks/data-lakehouse-iceberg-trino-spark/hive-metastores.yaml, stacks/dual-hive-hdfs-s3/hive.yaml, stacks/end-to-end-security/krb5.yaml, stacks/nifi-kafka-druid-superset-s3/druid.yaml, stacks/spark-trino-superset-s3/hive-metastore.yaml, stacks/trino-iceberg/hive-metastores.yaml, stacks/trino-superset-s3/hive-metastore.yaml
- stack/end-to-end-security: change krb5 version to 1.21.1
- stack/nifi-kafka-druid-superset-s3: use `credentialsSecret: druid-db-credentials` in druid cluster yaml
- adapt to hive breaking credential secret changes
=> Fix 24.7 demos

stacks/trino-iceberg/trino.yaml
This was leftover from stackabletech/operator-rs#652, and somehow got missed in the previous release demo testing.
This doesn't fix it completely, as the stacks/demos still point to the `main` branch, but that will be fixed separately in https://github.com/stackabletech/demos/issues/66
=> fix(trino-iceberg): remove invalid OpaCluster configuration

demos/hbase-hdfs-load-cycling-data/distcp-cycling-data.yaml, demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data/Dockerfile, demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data/load-test-data.yaml, stacks/data-lakehouse-iceberg-trino-spark/kafka.yaml, stacks/dual-hive-hdfs-s3/hdfs.yaml, stacks/end-to-end-security/hdfs.yaml, stacks/hdfs-hbase/hdfs.yaml, stacks/jupyterhub-pyspark-hdfs/hdfs.yaml, stacks/keycloak-opa-poc/hdfs.yaml
- use hadoop `3.3.4` instead of `3.4.0` (experimental)
- in `hbase-hdfs-load-cycling-data` demo use old `docker.stackable.tech/stackable/hadoop:3.3.6-stackable24.3.0` due to the removal of MapReduce in 24.7
- bump kafka version in lakehouse demo to `3.7.1`
=> More demo fixes

docs/modules/demos/pages/airflow-scheduled-job.adoc, docs/modules/demos/pages/data-lakehouse-iceberg-trino-spark.adoc, docs/modules/demos/pages/hbase-hdfs-load-cycling-data.adoc, docs/modules/demos/pages/index.adoc, docs/modules/demos/pages/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data.adoc, docs/modules/demos/pages/logging.adoc, docs/modules/demos/pages/nifi-kafka-druid-earthquake-data.adoc, docs/modules/demos/pages/nifi-kafka-druid-water-level-data.adoc, docs/modules/demos/pages/spark-k8s-anomaly-detection-taxi-data.adoc, docs/modules/demos/pages/trino-iceberg.adoc, docs/modules/demos/pages/trino-taxi-data.adoc
It seems that the page-aliases (for when demos used to be in the stackablectl repo) are only valid in nightly (because stackable-cockpit docs are only built on `main`.
Co-authored-by: xeniape <xenia.fischer@stackable.tech>
=> fix: remove page aliases to avoid duplication

demos/data-lakehouse-iceberg-trino-spark/create-nifi-ingestion-job.yaml, demos/data-lakehouse-iceberg-trino-spark/setup-superset.yaml, demos/demos-v2.yaml, demos/nifi-kafka-druid-earthquake-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-earthquake-data/setup-superset.yaml, demos/nifi-kafka-druid-water-level-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-water-level-data/setup-superset.yaml, demos/signal-processing/create-nifi-ingestion-job.yaml, demos/spark-k8s-anomaly-detection-taxi-data/setup-superset.yaml, demos/trino-taxi-data/setup-superset.yaml, docs/modules/demos/pages/data-lakehouse-iceberg-trino-spark.adoc, stacks/_templates/jupyterhub.yaml, stacks/airflow/airflow.yaml, stacks/signal-processing/jupyterhub.yaml, stacks/stacks-v2.yaml
=> fix: use release-23.11 branch references

stacks/_templates/vector-aggregator.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
> [!CAUTION]
> This PR is raised against the `next` branch so that demos aren't broken (resolved in future by https://github.com/stackabletech/stackable-cockpit/issues/310)
=> chore: Bump Vector to 0.40.0

stacks/airflow/airflow.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
> [!CAUTION]
> This PR is raised against the `next` branch so that demos aren't broken (resolved in future by https://github.com/stackabletech/stackable-cockpit/issues/310)
=> chore(airflow): bump version to 2.9.3

stacks/_templates/vector-aggregator.yaml
Upgrade the Vector aggregator to version 0.41.1
part of stackabletech/docker-images#845
Comment removed because the label is set on the pod:
```diff
-  podLabels: # Doesn't seem to work?
+  podLabels:
stackable.tech/vendor: Stackable
```
```shell
$ kubectl get pods vector-aggregator-0 -o yaml
apiVersion: v1
kind: Pod
metadata:
namespace: default
name: vector-aggregator-0
labels:
app.kubernetes.io/component: Aggregator
app.kubernetes.io/instance: vector-aggregator
app.kubernetes.io/name: vector
apps.kubernetes.io/pod-index: "0"
controller-revision-hash: vector-aggregator-5498ff4f5d
stackable.tech/vendor: Stackable
statefulset.kubernetes.io/pod-name: vector-aggregator-0
vector.dev/exclude: "true"
```
=> chore: Upgrade the Vector aggregator

.yamllint.yaml, stacks/keycloak-opa-poc/druid.yaml, stacks/nifi-kafka-druid-superset-s3/druid.yaml
Part of https://github.com/stackabletech/docker-images/issues/833
=> chore(druid): Bump to 30.0.0

.github/workflows/dev_nifi.yaml, demos/signal-processing/Dockerfile-nifi
Part of https://github.com/stackabletech/infrastructure/issues/143
=> ci: Add workflow for custom nifi image

.yamllint.yaml, stacks/_templates/jupyterhub.yaml, stacks/_templates/keycloak.yaml, stacks/_templates/minio-distributed-small.yaml, stacks/_templates/minio-distributed.yaml, stacks/_templates/minio.yaml, stacks/_templates/opensearch-dashboards.yaml, stacks/_templates/opensearch.yaml, stacks/_templates/postgresql-airflow.yaml, stacks/_templates/postgresql-druid.yaml, stacks/_templates/postgresql-hive-iceberg.yaml, stacks/_templates/postgresql-hive.yaml, stacks/_templates/postgresql-hivehdfs.yaml, stacks/_templates/postgresql-hives3.yaml, stacks/_templates/postgresql-superset.yaml, stacks/_templates/postgresql-timescaledb.yaml, stacks/_templates/prometheus.yaml, stacks/_templates/redis-airflow.yaml, stacks/_templates/vector-aggregator.yaml, stacks/observability/grafana-loki.yaml, stacks/observability/grafana-tempo.yaml, stacks/observability/grafana.yaml, stacks/observability/jaeger.yaml, stacks/observability/opentelemetry-operator.yaml, stacks/signal-processing/grafana.yaml, stacks/signal-processing/jupyterhub.yaml
Part of https://github.com/stackabletech/issues/issues/658
=> chore: Bump Helm charts

docs/modules/demos/pages/nifi-kafka-druid-water-level-data.adoc
https://github.com/stackabletech/issues/issues/658#issuecomment-2476404021
=> Update nifi-kafka-druid-water-level-data demo docs for 24.11

stacks/stacks-v2.yaml
As we already bumped the stack and demo manifests before the 24.11 release in https://github.com/stackabletech/demos/pull/116, we should at least use the dev versions, so that the demos are not completely broken.
This avoids the need for the users to run `stackablectl release in dev && stackablectl demo in trino-taxi-data --skip-release`
=> fix: Use dev release for stacks

.scripts/update_refs.sh
`|` was a bad delimiter because one expression contains an or. Instead of escaping `|` for the or, it is better to use a less common character as the delimiter.
Fixes #132
=> fix: Use different delimter in sed expressions

stacks/end-to-end-security/superset.yaml
Otherwise it breaks with:
```
ERROR [flask_migrate] Error: Requested revision 17fcea065655 overlaps with other requested revisions b7851ee5522f
```
The latter revision being the one that exists in the uploaded dump.
<details><summary>:poop: fails</summary>
1. ![image](https://github.com/user-attachments/assets/84e5fca7-ebed-45cf-9a9f-125823709054)
2. ![image](https://github.com/user-attachments/assets/740d30f0-9b6a-4f2f-82a7-a994b705a701)
</details>
=> fix(stack/end-to-end-security): Skip DB restore if the DB exists

stacks/_templates/vector-aggregator.yaml
Updating `vector-aggregator` helm chart to `0.39.0` with app version `0.43.1` following https://github.com/stackabletech/docker-images/issues/967
=> Updating helm chart to app version 0.43.1

stacks/data-lakehouse-iceberg-trino-spark/kafka.yaml, stacks/nifi-kafka-druid-superset-s3/kafka.yaml
Part of https://github.com/stackabletech/docker-images/issues/968.
Bump demos to use Kafka 3.9.0.
=> chore(kafka): Bump to 3.9.0

stacks/end-to-end-security/rbac.yaml, stacks/end-to-end-security/setup-postgresql.yaml, stacks/end-to-end-security/superset.yaml, stacks/stacks-v2.yaml
The postgresl dump file contains the dashboard assets, created under an earlier version of superset (3.x). Since the upgrade to 4.x there appears to be changes made (by flask?) to the database that overwrite the restore action. This PR move the DB initialization to a separate step. It now looks like this:
- postgres installed via helm
- once the postgres statefulset is ready, a job runs that downloads the dump file and restores it
- superset waits for this job to complete but does not restore anything (although there will a DB migration due to the version differences)
Logged in via Keycloak:
=> fix: E2E Security demo - Separate DB setup from superset resource

demos/demos-v2.yaml, stacks/jupyterhub-keycloak/jupyterhub.yaml, stacks/stacks-v2.yaml
These paths were not re-set following the merge of the demo.
=> fix: Demo/Stack URLs for JupyterHub-Keycloak demo

.github/workflows/dev_nifi.yaml, demos/demos-v2.yaml, demos/nifi-kafka-druid-earthquake-data/create-druid-ingestion-job.yaml, demos/nifi-kafka-druid-earthquake-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-earthquake-data/serviceaccount.yaml, demos/nifi-kafka-druid-earthquake-data/setup-superset.yaml, demos/nifi-kafka-druid-water-level-data/create-druid-ingestion-job.yaml, demos/nifi-kafka-druid-water-level-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-water-level-data/serviceaccount.yaml, demos/nifi-kafka-druid-water-level-data/setup-superset.yaml, demos/signal-processing/Dockerfile-nifi, demos/signal-processing/DownloadAndWriteToDB.xml, demos/signal-processing/create-nifi-ingestion-job.yaml, demos/signal-processing/create-timescale-tables.yaml, docs/modules/demos/pages/signal-processing.adoc, stacks/data-lakehouse-iceberg-trino-spark/nifi.yaml, stacks/nifi-kafka-druid-superset-s3/nifi.yaml, stacks/signal-processing/nifi.yaml
Part of https://github.com/stackabletech/docker-images/issues/966.
- Update NiFi demos and custom image to 1.28.1
- Update the postgres jar and move it to a more appropriate image repository (it is not related to timescale).
- Update the docs to explain which dashboard is being described.
- Improve readability of the initialisation jobs.
> [!IMPORTANT]
> Despite the branch name, we are not bumping the demos to 2.2.0 as they rely on uploading templates.
=> chore(nifi): Bump to 1.28.1, upgrade postgres jdbc driver

demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data/load-test-data.yaml, stacks/dual-hive-hdfs-s3/hdfs.yaml, stacks/end-to-end-security/hdfs.yaml, stacks/hdfs-hbase/hdfs.yaml, stacks/jupyterhub-pyspark-hdfs/hdfs.yaml, stacks/keycloak-opa-poc/hdfs.yaml
part of https://github.com/stackabletech/docker-images/issues/1018
- I did not touch a 3.3.6-stackable24.7 image (cycling data, not available anymore)
- there are some 3.3.4 references but used for spark
=> chore: Update HDFS to 3.4.1

stacks/end-to-end-security/rbac.yaml, stacks/end-to-end-security/setup-postgresql.yaml, stacks/end-to-end-security/superset.yaml, stacks/stacks-v2.yaml
Backport of https://github.com/stackabletech/demos/pull/151
Currently `stackablectl demo in end-to-end-security` is broken, this PR fixes that.
Adjusted the commit to the correct versions and branches
=> fix(backport): E2E Security demo - Separate DB setup from superset resource

docs/modules/demos/pages/airflow-scheduled-job.adoc, stacks/airflow/airflow.yaml
fixes OOM kills with 2.10.4 in airflow-scheduled-job
=> airflow-scheduled-job: increase scheduler memory limit

docs/modules/demos/pages/signal-processing.adoc
Came up in https://github.com/stackabletech/demos/issues/157#issuecomment-2728840121.
=> docs(demo/signal-processing): Add note on index violation when re-running

demos/spark-k8s-anomaly-detection-taxi-data/create-spark-anomaly-detection-job.yaml, stacks/spark-trino-superset-s3/s3-connection.yaml, stacks/stacks-v2.yaml
- **fix: better encapsulation for the anomaly detection stack**
- **remove unused dependency**
=> fix: better encapsulation for the anomaly demo

stacks/stacks-v2.yaml, stacks/trino-superset-s3/s3-connection.yaml
Fixes problems where Trino fails to connect to Minio due to TLS subject name verification.
=> fix(stack/trino-superset-s3): Use FQDN for minio, restrict to default namespace

demos/demos-v2.yaml
Follow up to https://github.com/stackabletech/demos/pull/176, updates memory resources in demos file also.
=> chore: update memory resources for trino-iceberg demo

docs/modules/demos/pages/index.adoc
Adds some documentation about where to find the code for the demos and how it is composed.
=> docs: add documentation for demo code

demos/demos-v2.yaml
Fix documentation link for demos
=> fix: documentation link

stacks/end-to-end-security/hive-metastore.yaml
Use hive 4.0.0 instead of 4.0.1, came up during https://github.com/stackabletech/demos/issues/187, cherry-picked from the `release-25.3` branch into main.
=> fix(end-to-end-security): Downgrade Hive metastore to 4.0.0 (#189)

demos/data-lakehouse-iceberg-trino-spark/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-earthquake-data/create-nifi-ingestion-job.yaml, demos/nifi-kafka-druid-water-level-data/create-nifi-ingestion-job.yaml, demos/signal-processing/create-nifi-ingestion-job.yaml
While the demos are currently working, NiFi 2 reports a status drift to the versioned components when comparing the deployed state with the state in Git. This is wrong, but we can't really work around it and it might irritate users.
Also, we saw some problems related to Github's rate limits when installing NiFi demos too often on the same machine.
This PR drops the whole process of versioning, since it is not needed for the demos. It was just our first approach as a replacement for the "templates" functionality that was removed with NiFi 2. Instead of using versioning, we now download the JSON files from Github via HTTP and then directly create the Flows via NiFis `/process-groups/upload` API.
=> feat(nifi): Restore flows directly from JSON file instead of using versioning

stacks/_templates/vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 (chart version 0.42.1)
=> chore: Bump vector to 0.46.1

stacks/data-lakehouse-iceberg-trino-spark/trino.yaml, stacks/dual-hive-hdfs-s3/trino.yaml, stacks/end-to-end-security/opa.yaml, stacks/keycloak-opa-poc/opa.yaml, stacks/trino-iceberg/trino.yaml, stacks/trino-superset-s3/trino.yaml
Part of https://github.com/stackabletech/docker-images/issues/1084.
- Bump OPA to `1.4.2` in stacks
=> chore(stacks): Bump OPA to 1.4.2

.github/workflows/dev_jupyter-pyspark-with-alibi-detect.yaml, .github/workflows/dev_nifi.yaml, .github/workflows/reusable_build_image.yaml
This PR enables the demo image build workflows to send notifications to Slack.
=> ci: Add failure notification job

.github/workflows/dev_nifi.yaml, stacks/data-lakehouse-iceberg-trino-spark/nifi.yaml, stacks/nifi-kafka-druid-superset-s3/nifi.yaml, stacks/signal-processing/nifi.yaml
Part of https://github.com/stackabletech/docker-images/issues/1079.
=> chore(nifi): Bump to 2.4.0

stacks/_templates/vector-aggregator.yaml
Part of: https://github.com/stackabletech/docker-images/issues/1146
=> chore: bump vector chart to 0.43.0

.github/ISSUE_TEMPLATE/pre-release-chart-updates.md, .scripts/update_helm_charts.py, shell.nix, stacks/observability/opentelemetry-operator.yaml
The script is not perfect but was easy to develop with my friend GPT and I think is already helpful.
As it states on startup it's best-effort only. But even if it bumps only 50% of the charts, that halves the effort.
Because of this I personally would prefer to not review it too thoroughly :sweat_smile: 
It currently finds the following bumps. Let me know if we want to apply them (excluding opensearch)
```diff
diff --git a/stacks/_templates/opensearch-dashboards.yaml b/stacks/_templates/opensearch-dashboards.yaml
index 5903fe6..439a353 100644
--- a/stacks/_templates/opensearch-dashboards.yaml
+++ b/stacks/_templates/opensearch-dashboards.yaml
@@ -4,7 +4,7 @@ name: opensearch-dashboards
repo:
name: opensearch-dashboards
url: https://opensearch-project.github.io/helm-charts
-version: 2.30.0 …
```
=> chore: Add basic script to upgrade most helm-charts

docs/modules/demos/pages/trino-taxi-data.adoc
Part of https://github.com/stackabletech/demos/issues/242
Update the stacklet list output.
> [!NOTE]
> The metrics entry is removed. I assume that is intentional.
=> docs(demo/trino-taxi-data): Update stacklet list output

docs/modules/demos/pages/hbase-hdfs-load-cycling-data.adoc
The listener endpoints are updated, as well as a few minor formatting line-breaks.
=> fix(demo/hbase-hdfs-load-cycling-data): Update stacklet addresses

docs/modules/demos/pages/spark-k8s-anomaly-detection-taxi-data.adoc
> [!TIP]
> Companion PR: https://github.com/stackabletech/demos/pull/276
=> docs(spark-k8s-anomaly-detection-taxi-data): Add note about accessing the job pod

demos/nifi-kafka-druid-water-level-data/create-druid-ingestion-job.yaml
No one ever noticed :sweat_smile:
=> fix: Remove typo in Druid compaction Job JSON

demos/demos-v2.yaml, docs/modules/demos/pages/hbase-hdfs-load-cycling-data.adoc, stacks/hdfs-hbase/hbase.yaml, stacks/stacks-v2.yaml
The hbase shell doesn't have enough memory to test this demo.
See https://github.com/stackabletech/issues/issues/752
=> fix: increase hbase master memory to avoid the hbase shell being killed

stacks/end-to-end-security/trino-regorules.yaml
Improve the performance of the Trino Rego rules
see stackabletech/trino-operator#782
The new Trino rules were copied from the integration test to the end-to-end-security stack.
The [end-to-end-security demo](https://docs.stackable.tech/home/stable/demos/end-to-end-security/) was successfully tested with the new rules.
The performance of the Trino rules in the end-to-end-security stack was improved. Batch queries are now significantly faster.
=> Improve the performance of the Trino Rego rules

demos/data-lakehouse-iceberg-trino-spark/load-test-data.yaml, demos/jupyterhub-keycloak/load-gas-data.yaml, demos/spark-k8s-anomaly-detection-taxi-data/load-test-data.yaml, demos/trino-taxi-data/load-test-data.yaml, stacks/_templates/postgresql-airflow.yaml, stacks/_templates/postgresql-druid.yaml, stacks/_templates/postgresql-hive-iceberg.yaml, stacks/_templates/postgresql-hive.yaml, stacks/_templates/postgresql-hivehdfs.yaml, stacks/_templates/postgresql-hives3.yaml, stacks/_templates/postgresql-superset.yaml, stacks/_templates/redis-airflow.yaml, stacks/authentication/openldap-tls.yaml, stacks/end-to-end-security/setup-postgresql.yaml
Part of https://github.com/stackabletech/issues/issues/749 and follow up to https://github.com/stackabletech/demos/pull/290
This PR updates the demos of the 25.7 release to use bitnamilegacy.
=> chore: update demos to use bitnamilegacy

stacks/monitoring/prometheus-service-monitors.yaml
Add ServiceMonitor for OpenSearch to the monitoring stack
see also https://docs.stackable.tech/home/nightly/opensearch/usage-guide/monitoring/
=> feat: Add ServiceMonitor for OpenSearch to the monitoring stack

demos/data-lakehouse-iceberg-trino-spark/create-spark-ingestion-job.yaml, demos/end-to-end-security/create-spark-report.yaml, demos/spark-k8s-anomaly-detection-taxi-data/create-spark-anomaly-detection-job.yaml, stacks/airflow/airflow.yaml, stacks/jupyterhub-pyspark-hdfs/jupyterlab.yaml, stacks/jupyterhub-pyspark-hdfs/notebook.ipynb, stacks/jupyterhub-pyspark-hdfs/spark_connect.yaml
Part of: https://github.com/stackabletech/docker-images/issues/1273
Depends on:
- https://github.com/stackabletech/docker-images/pull/1280
- https://github.com/stackabletech/spark-k8s-operator/pull/610
=> chore(spark): bump version to 4.0.1
